title: "Nikolaj Mikkelsen"
description: "Interaction Design"
about: "Interaction Design"
location: "Aarhus, Denmark"
email: "nikolaj.c.mikkelsen@gmail.com"
baseurl: ""
url: "ncmikkelsen.github.io/" # replace by your site's url
twitter_username: "@ncmikkelsen"
github_username:  "ncmikkelsen"

# Collections
collections:
    projects:
        link: ""
        name: ""
        description: ""
        output: true
        permalink: /projects/:path/


# google analytics tracking code, please change the value
g_analytics: "UA-85757330-1"

# language settings
isolang: en
close_btn: "Close"
home_btn: "Home"
projects_btn: "Projects"
posts_btn: "Posts"
name_badge: "an article by"
rss_badge: "Subscribe feed!"

# build settings
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    tab_width: 4

# third party gems
gems:
  - jekyll-paginate
  - jekyll-gist
  - jemoji

whitelist:
  - jekyll-paginate
  - jekyll-gist
  - jemoji

# exclude files
exclude:
  - LICENSE
  - README.md
